- !!python/object:__main__.DataColumnIntegerIncreasing
  name: Order
  last: 0
  start: 40000
- !!python/object:__main__.DataColumnList
  name: Project
  values:
  - Project1
  - Project2
  - Project3
- !!python/object:__main__.DataColumnList
  name: Site
  values:
  - Site1
  - Site2
  - Site3
- !!python/object:__main__.DataColumnCombine
  delimiter: .
  name: WBS
  previous: 2
- !!python/object:__main__.DataColumn
  name: Description
- !!python/object:__main__.DataColumnInteger
  high: 5000
  low: 1000
  name: Estimated
- !!python/object:__main__.DataColumnIntegerDelta
  delta: 25
  name: Actual
- !!python/object:__main__.DataColumnDateIncreasing
  name: Start
  rows_per_day: 6
  start: 2020-01-01
  last_row: 0
  last_date: 0
- !!python/object:__main__.DataColumnDateDelta
  delta: 5
  name: Finish
- !!python/object:__main__.DataColumnList
  name: Priority
  values:
  - '1'
  - '2'
  - '3'
  - '4'
- !!python/object:__main__.DataColumnDictionary
  name: Priority Text
  values:
    '1': Emergency
    '2': High
    '3': Medium
    '4': Low
- !!python/object:__main__.DataColumnList
  name: Lat
  values:
  - '37.778549194336'
  - '37.77717590332'
  - '37.780332'
- !!python/object:__main__.DataColumnDictionary
  name: Lon
  values:
    '37.77717590332': '-122.4227142334'
    '37.778549194336': '-122.42134094238'
    '37.780332': '-122.418898'
